"""Concurrency-safe writes to the plain-markdown memory tiers (session/wiki/failures).

Why: these tiers were written by Claude's Edit tool and the flush_session hook
with no lock, so concurrent fleet sessions clobbered each other (H1,
PLAN-multisession-fleet-reverify). Every write here runs the whole read-modify-
write INSIDE ``exclusive_lock``; the lock anchor is a separate ``.lock`` sentinel,
never the target ``.md`` (locking the target would break under atomic-replace —
ADR-001/002). Session memory always targets the BASE repo, never a worktree copy,
so the CLI and the hook take the same lock (ADR-005).
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

from harness_maker import command_registry
from harness_maker.io_utils import atomic_write
from harness_maker.memory._locking import exclusive_lock

OPEN_MARKER = "<!-- @hm:user:entries -->"
CLOSE_MARKER = "<!-- @hm:/user:entries -->"

_HEADING_RE = re.compile(r"^##\s+\[(?P<tier>[^:\]]+):(?P<cat>[^\]]+)\]\s+(?P<slug>\S+)")
_FAILURE_META_RE = re.compile(
    r"\|\s*(?P<date>\d{4}-\d{2}-\d{2})\s*\|\s*count:\s*(?P<count>\S+)\s*$"
)
# slug/category must round-trip through `_HEADING_RE` cleanly — a `]`, `|`, or
# whitespace would make the heading un-reparseable (silent duplicate on the next
# upsert instead of replace). Pin them to the documented kebab-case shape.
_SLUG_RE = re.compile(r"[a-z0-9][a-z0-9-]{0,39}")
_CATEGORY_RE = re.compile(r"[a-z0-9-]+")


class MemoryBlockError(Exception):
    """A tier file is malformed in a way that makes a safe upsert impossible.

    Fail-closed (non-zero CLI exit) rather than guess — a wrong guess silently
    overwrites the wrong entry or drops the close marker (a documented silent
    corruption mode).
    """


def _utcnow() -> datetime:
    return datetime.now(tz=UTC)


def _base_root(root: Path | str) -> Path:
    """Resolve to the base repo root, stripping a ``.worktrees/<name>`` suffix.

    Memory tiers are shared project memory committed by wrapup from the base
    repo; a worktree copy is ephemeral. Resolving here also defeats relative /
    symlink spelling differences so the CLI and the hook compute byte-identical
    lock paths (ADR-005).
    """
    resolved = Path(root).resolve()
    parts = resolved.parts
    if ".worktrees" in parts:
        # last occurrence — only the trailing `<base>/.worktrees/<name>` is a real
        # worktree suffix; a `.worktrees` segment higher up belongs to the base path.
        idx = max(i for i, p in enumerate(parts) if p == ".worktrees")
        if idx > 0:
            return Path(*parts[:idx])
    return resolved


def _memory_dir(root: Path | str) -> Path:
    return _base_root(root) / ".claude" / "memory"


def session_lock_path(root: Path | str) -> Path:
    return _memory_dir(root) / ".session.lock"


def wiki_lock_path(root: Path | str) -> Path:
    return _memory_dir(root) / ".wiki.lock"


def failures_lock_path(root: Path | str) -> Path:
    return _memory_dir(root) / ".failures.lock"


def session_header(today: str) -> str:
    """Shared header so the CLI and flush_session hook produce identical files."""
    return (
        f"# Session Log — {today}\n\n"
        "> Auto-generated by harness-maker.\n"
        "> Format: `## [category:slug] description | HH:MM UTC | stage:name`\n\n"
    )


def append_session(root: Path | str, body: str, *, today: str | None = None) -> Path:
    """Append one entry to today's session log under the session lock."""
    today = today or _utcnow().strftime("%Y-%m-%d")
    log_file = _memory_dir(root) / "session" / f"{today}.md"
    with exclusive_lock(session_lock_path(root)):
        entry = body.strip("\n") + "\n"
        existing = log_file.read_text(encoding="utf-8") if log_file.exists() else ""
        if existing.strip():
            new_text = existing.rstrip("\n") + "\n\n" + entry
        else:
            new_text = session_header(today) + entry
        atomic_write(log_file, new_text)
    return log_file


def _locate_block(text: str) -> tuple[list[str], int, int] | None:
    """Return (lines, open_idx, close_idx) or None when the file has no block.

    None = benign "fresh / legacy" file (no markers at all) → caller creates the
    block. Any partial/duplicated marker state is fail-closed.
    """
    lines = text.splitlines()
    opens = [i for i, ln in enumerate(lines) if ln.strip() == OPEN_MARKER]
    closes = [i for i, ln in enumerate(lines) if ln.strip() == CLOSE_MARKER]
    if not opens and not closes:
        return None
    if len(opens) > 1 or len(closes) > 1:
        raise MemoryBlockError(
            f"duplicate @hm:user:entries marker (open={len(opens)} close={len(closes)})"
        )
    if len(opens) != 1 or len(closes) != 1:
        raise MemoryBlockError("missing @hm:user:entries open or close marker")
    if opens[0] > closes[0]:
        raise MemoryBlockError("close marker precedes open marker")
    return lines, opens[0], closes[0]


def _entry_headings(lines: list[str], open_idx: int, close_idx: int) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for i in range(open_idx + 1, close_idx):
        m = _HEADING_RE.match(lines[i])
        if m:
            out.append((i, m.group("slug")))
    return out


def _parse_failure_meta(heading: str) -> tuple[str, int]:
    m = _FAILURE_META_RE.search(heading)
    if not m:
        raise MemoryBlockError(f"failure heading missing '| <date> | count:<N>': {heading!r}")
    try:
        return m.group("date"), int(m.group("count"))
    except ValueError as exc:
        raise MemoryBlockError(f"non-integer count in failure heading: {heading!r}") from exc


def _collapse_note(text: str) -> str:
    """Collapse whitespace to a single line, re-checking for markers post-collapse.

    A marker split across a newline (``<!-- @hm:user:entries\n-->``) slips past the raw
    substring guard but reforms once ``split()``/join drops the newline — guard here too.
    """
    collapsed = " ".join(text.split())
    if OPEN_MARKER in collapsed or CLOSE_MARKER in collapsed:
        raise MemoryBlockError("occurrence note contains a marker string")
    return collapsed


def _new_entry_body(
    *, is_failure: bool, body_lines: list[str], occurrence_note: str | None, today: str
) -> list[str]:
    """Body lines for a brand-new failure entry.

    Seeds from ``occurrence_note`` when no ``--body-file`` was supplied — fail-closed on
    an empty note and bullet-prefixed so a heading-shaped note can never inject a phantom
    ``## [...]`` heading. Shared by the marker-absent and no-match creation paths so both
    honor the same invariant (a ``count:N`` entry never outruns its recorded evidence).
    """
    if is_failure and occurrence_note is not None and not "".join(body_lines).strip():
        occ_text = _collapse_note(occurrence_note)
        if not occ_text:
            raise MemoryBlockError(
                "empty occurrence note on a new failure — refusing an evidence-less entry"
            )
        return [f"- [{today}] {occ_text}"]
    return body_lines


def _upsert(
    *,
    root: Path | str,
    target_file: Path,
    lock_path: Path,
    slug: str,
    body: str,
    is_failure: bool,
    category: str,
    today: str,
    title: str,
    occurrence_note: str | None = None,
) -> Path:
    if not _SLUG_RE.fullmatch(slug):
        raise MemoryBlockError(f"invalid slug {slug!r} (expected kebab-case, ≤40 chars)")
    if not _CATEGORY_RE.fullmatch(category):
        raise MemoryBlockError(f"invalid category {category!r} (expected [a-z0-9-])")
    if OPEN_MARKER in body or CLOSE_MARKER in body:
        raise MemoryBlockError("entry body contains a marker string")
    if occurrence_note is not None and (
        OPEN_MARKER in occurrence_note or CLOSE_MARKER in occurrence_note
    ):
        raise MemoryBlockError("occurrence note contains a marker string")
    body_lines = body.strip("\n").split("\n")
    if any(_HEADING_RE.match(ln) for ln in body_lines):
        # a heading-shaped body line becomes a phantom entry on the next upsert's
        # `_entry_headings` scan → silent truncation (wiki) or tier DoS (failures).
        raise MemoryBlockError("entry body contains an entry-heading line (`## [tier:slug] …`)")

    def wiki_heading() -> str:
        return f"## [wiki:{category}] {slug} | {today}"

    def fail_heading(date: str, count: int) -> str:
        return f"## [fail:{category}] {slug} | {date} | count:{count}"

    with exclusive_lock(lock_path):
        text = target_file.read_text(encoding="utf-8") if target_file.exists() else ""
        located = _locate_block(text)

        if located is None:
            if text.strip():
                # File has real content but lost BOTH markers (corruption). Creating
                # a fresh block here would split it into unmanaged-old + managed-new
                # halves — the dedup/count history would silently vanish. Fail closed.
                raise MemoryBlockError(
                    f"{target_file} has content but no @hm:user:entries block — refusing "
                    "to split it; restore the markers manually"
                )
            sys.stderr.write(
                f"[memory_md] WARN: {target_file} has no @hm:user:entries block — creating it\n"
            )
            heading = fail_heading(today, 1) if is_failure else wiki_heading()
            seed_body = _new_entry_body(
                is_failure=is_failure,
                body_lines=body_lines,
                occurrence_note=occurrence_note,
                today=today,
            )
            prefix = f"# {title} Index\n\n"
            new_text = (
                prefix
                + OPEN_MARKER
                + "\n"
                + "\n".join([heading, *seed_body])
                + "\n"
                + CLOSE_MARKER
                + "\n"
            )
            atomic_write(target_file, new_text)
            return target_file

        lines, open_idx, close_idx = located
        headings = _entry_headings(lines, open_idx, close_idx)
        matches = [idx for idx, s in headings if s == slug]
        if len(matches) > 1:
            raise MemoryBlockError(
                f"duplicate entry for slug {slug!r} — cannot pick which to replace"
            )

        if matches:
            start = matches[0]
            later = sorted(idx for idx, _ in headings if idx > start)
            end = later[0] if later else close_idx
            if is_failure:
                old_date, old_count = _parse_failure_meta(lines[start])
                # occurrence-log (ADR-002): preserve the original body + prior
                # bullets, append one dated occurrence, count++. Append and
                # increment are atomic — an empty note is fail-closed so a
                # count:N entry never outruns its recorded evidence.
                source = occurrence_note if occurrence_note is not None else " ".join(body_lines)
                occ_text = _collapse_note(source)
                if not occ_text:
                    raise MemoryBlockError(
                        "empty occurrence note on a matched failure — refusing "
                        "count++ without evidence"
                    )
                heading = fail_heading(old_date, old_count + 1)
                existing_body = lines[start + 1 : end]
                new_lines = (
                    lines[:start]
                    + [heading, *existing_body, f"- [{today}] {occ_text}"]
                    + lines[end:]
                )
            else:
                heading = wiki_heading()
                new_lines = lines[:start] + [heading, *body_lines] + lines[end:]
        else:
            new_body = _new_entry_body(
                is_failure=is_failure,
                body_lines=body_lines,
                occurrence_note=occurrence_note,
                today=today,
            )
            heading = fail_heading(today, 1) if is_failure else wiki_heading()
            new_lines = lines[:close_idx] + [heading, *new_body] + lines[close_idx:]

        atomic_write(target_file, "\n".join(new_lines) + "\n")
    return target_file


def upsert_wiki(
    root: Path | str, slug: str, category: str, body: str, *, today: str | None = None
) -> Path:
    """Insert-or-replace a wiki entry by slug, inside the marker block, under the lock."""
    today = today or _utcnow().strftime("%Y-%m-%d")
    return _upsert(
        root=root,
        target_file=_memory_dir(root) / "wiki.md",
        lock_path=wiki_lock_path(root),
        slug=slug,
        body=body,
        is_failure=False,
        category=category,
        today=today,
        title="Wiki",
    )


def upsert_failure(
    root: Path | str,
    slug: str,
    category: str,
    body: str,
    *,
    today: str | None = None,
    occurrence_note: str | None = None,
) -> Path:
    """Insert-or-count++ a failure entry by slug, inside the marker block, under the lock.

    On a matched slug the original body is preserved and ``occurrence_note`` (or, as a
    safety net, the collapsed ``body``) is appended as a dated bullet — see ADR-002.
    """
    today = today or _utcnow().strftime("%Y-%m-%d")
    return _upsert(
        root=root,
        target_file=_memory_dir(root) / "failures.md",
        lock_path=failures_lock_path(root),
        slug=slug,
        body=body,
        is_failure=True,
        category=category,
        today=today,
        title="Failures",
        occurrence_note=occurrence_note,
    )


# ── CLI ──────────────────────────────────────────────────────────────────────


def _read_body(args: argparse.Namespace) -> str:
    if args.body is not None:
        return str(args.body)
    if args.body_file is not None:
        return Path(args.body_file).read_text(encoding="utf-8")
    return sys.stdin.read()


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m harness_maker.memory_md",
        description="Concurrency-safe (flock) writes to the markdown memory tiers.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    def _common(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--root", default=".", type=Path)
        sp.add_argument("--body", default=None, help="Entry body (prefer --body-file/stdin).")
        sp.add_argument("--body-file", default=None, help="Path to a file holding the entry body.")
        sp.add_argument("--today", default=None, help="YYYY-MM-DD (deterministic date).")

    a = sub.add_parser("append-session", help="Append an entry to today's session log.")
    _common(a)

    w = sub.add_parser("upsert-wiki", help="Insert-or-replace a wiki entry by slug.")
    _common(w)
    w.add_argument("--slug", required=True)
    w.add_argument("--category", required=True)

    f = sub.add_parser("upsert-failure", help="Insert-or-count++ a failure entry by slug.")
    _common(f)
    f.add_argument("--slug", required=True)
    f.add_argument("--category", required=True)
    f.add_argument(
        "--occurrence-note",
        default=None,
        help="On a matched slug, append this one-line dated occurrence (count++).",
    )

    return p


def main(argv: list[str] | None = None) -> int:
    _guard = command_registry.guard_or_none("memory_md", argv)
    if _guard is not None:
        return _guard
    args = _build_parser().parse_args(argv)
    try:
        # For upsert-failure with --occurrence-note, the note is the payload — do
        # NOT read stdin (that would block when no body/--body-file is supplied).
        occ = getattr(args, "occurrence_note", None)
        if occ is not None and (args.body is not None or args.body_file is not None):
            # Mutually exclusive: silently dropping the richer body is a footgun.
            raise MemoryBlockError(
                "--occurrence-note is mutually exclusive with --body/--body-file"
            )
        body = "" if (args.cmd == "upsert-failure" and occ is not None) else _read_body(args)
        if args.cmd == "append-session":
            path = append_session(args.root, body, today=args.today)
        elif args.cmd == "upsert-wiki":
            path = upsert_wiki(args.root, args.slug, args.category, body, today=args.today)
        elif args.cmd == "upsert-failure":
            path = upsert_failure(
                args.root, args.slug, args.category, body, today=args.today, occurrence_note=occ
            )
        else:  # pragma: no cover — argparse enforces a valid subcommand
            return 2
    except (MemoryBlockError, OSError, ValueError) as exc:
        sys.stderr.write(f"{args.cmd} failed: {exc}\n")
        return 1
    sys.stdout.write(str(path) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
