"""Concurrency-safe writes to the plain-markdown memory tiers (session/wiki/failures).

Why: these tiers were written by Claude's Edit tool and the flush_session hook
with no lock, so concurrent fleet sessions clobbered each other (H1,
PLAN-multisession-fleet-reverify). Every write here runs the whole read-modify-
write INSIDE ``exclusive_lock``; the lock anchor is a separate ``.lock`` sentinel,
never the target ``.md`` (locking the target would break under atomic-replace —
ADR-001/002). Session memory always targets the BASE repo, never a worktree copy,
so the CLI and the hook take the same lock (ADR-005).
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from harness_maker import command_registry
from harness_maker.io_utils import atomic_write
from harness_maker.memory._locking import exclusive_lock

OPEN_MARKER = "<!-- @hm:user:entries -->"
CLOSE_MARKER = "<!-- @hm:/user:entries -->"

_HEADING_RE = re.compile(r"^##\s+\[(?P<tier>[^:\]]+):(?P<cat>[^\]]+)\]\s+(?P<slug>\S+)")
_FAILURE_META_RE = re.compile(
    r"\|\s*(?P<date>\d{4}-\d{2}-\d{2})\s*\|\s*count:\s*(?P<count>\S+)\s*$"
)
# Two independent rules, deliberately NOT one pattern (ADR-004 of
# PLAN-second-opinion-invocation-and-slug-cap).
#
# `_SLUG_SAFE_RE` is the correctness floor and applies to EVERY slug.
#
# It is an ALLOWLIST, not a deny-three-characters rule. The reparse constraints
# alone (whitespace truncates `_HEADING_RE`'s `\S+`, `]` breaks the
# `[tier:category]` bracket, `|` collides with the `| date | count:N` meta) would
# be satisfied by `[^\s\]|]+` — but that admits `$`, backticks, `;`, `&`, and the
# slug's consumer is NOT only this module: `wrapup.md.j2` renders
# `--slug <existing-slug>` UNQUOTED inside a `!uv run …` Bash line, and
# `failures.md` is a committed deliverable. A heading carrying a command
# substitution with no whitespace would be grandfathered here and executed there
# on the next recurrence. Verified against the live corpus: all 307 existing
# wiki+failure slugs satisfy this allowlist, so tightening costs nothing.
#
# `_SLUG_NEW_RE` is the style rule and applies only to slugs that are NOT already
# present as an entry heading. 45/123 failure and 49/185 wiki slugs predate the
# cap, and two wiki slugs under it carry `_`/`.`; holding those to the new-slug
# rule made `count++` and in-place replacement unreachable for them — the writer
# refusing keys it wrote itself.
_SLUG_SAFE_RE = re.compile(r"[A-Za-z0-9._-]+")
_SLUG_NEW_RE = re.compile(r"[a-z0-9][a-z0-9-]{0,39}")
_CATEGORY_RE = re.compile(r"[a-z0-9-]+")


class MemoryBlockError(Exception):
    """A tier file is malformed in a way that makes a safe upsert impossible.

    Fail-closed (non-zero CLI exit) rather than guess — a wrong guess silently
    overwrites the wrong entry or drops the close marker (a documented silent
    corruption mode).
    """


def _utcnow() -> datetime:
    return datetime.now(tz=UTC)


def _base_root(root: Path | str) -> Path:
    """Resolve to the base repo root, stripping a ``.worktrees/<name>`` suffix.

    Memory tiers are shared project memory committed by wrapup from the base
    repo; a worktree copy is ephemeral. Resolving here also defeats relative /
    symlink spelling differences so the CLI and the hook compute byte-identical
    lock paths (ADR-005).
    """
    resolved = Path(root).resolve()
    parts = resolved.parts
    if ".worktrees" in parts:
        # last occurrence — only the trailing `<base>/.worktrees/<name>` is a real
        # worktree suffix; a `.worktrees` segment higher up belongs to the base path.
        idx = max(i for i, p in enumerate(parts) if p == ".worktrees")
        if idx > 0:
            return Path(*parts[:idx])
    return resolved


def _memory_dir(root: Path | str) -> Path:
    return _base_root(root) / ".claude" / "memory"


def session_lock_path(root: Path | str) -> Path:
    return _memory_dir(root) / ".session.lock"


def wiki_lock_path(root: Path | str) -> Path:
    return _memory_dir(root) / ".wiki.lock"


def failures_lock_path(root: Path | str) -> Path:
    return _memory_dir(root) / ".failures.lock"


def session_header(today: str) -> str:
    """Shared header so the CLI and flush_session hook produce identical files."""
    return (
        f"# Session Log — {today}\n\n"
        "> Auto-generated by harness-maker.\n"
        "> Format: `## [category:slug] description | HH:MM UTC | stage:name`\n\n"
    )


def append_session(root: Path | str, body: str, *, today: str | None = None) -> Path:
    """Append one entry to today's session log under the session lock."""
    today = today or _utcnow().strftime("%Y-%m-%d")
    log_file = _memory_dir(root) / "session" / f"{today}.md"
    with exclusive_lock(session_lock_path(root)):
        entry = body.strip("\n") + "\n"
        existing = log_file.read_text(encoding="utf-8") if log_file.exists() else ""
        if existing.strip():
            new_text = existing.rstrip("\n") + "\n\n" + entry
        else:
            new_text = session_header(today) + entry
        atomic_write(log_file, new_text)
    return log_file


def _locate_block(text: str) -> tuple[list[str], int, int] | None:
    """Return (lines, open_idx, close_idx) or None when the file has no block.

    None = benign "fresh / legacy" file (no markers at all) → caller creates the
    block. Any partial/duplicated marker state is fail-closed.
    """
    lines = text.splitlines()
    opens = [i for i, ln in enumerate(lines) if ln.strip() == OPEN_MARKER]
    closes = [i for i, ln in enumerate(lines) if ln.strip() == CLOSE_MARKER]
    if not opens and not closes:
        return None
    if len(opens) > 1 or len(closes) > 1:
        raise MemoryBlockError(
            f"duplicate @hm:user:entries marker (open={len(opens)} close={len(closes)})"
        )
    if len(opens) != 1 or len(closes) != 1:
        raise MemoryBlockError("missing @hm:user:entries open or close marker")
    if opens[0] > closes[0]:
        raise MemoryBlockError("close marker precedes open marker")
    return lines, opens[0], closes[0]


def _entry_headings(lines: list[str], open_idx: int, close_idx: int) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for i in range(open_idx + 1, close_idx):
        m = _HEADING_RE.match(lines[i])
        if m:
            out.append((i, m.group("slug")))
    return out


def _validate_new_slug(slug: str) -> None:
    """Style rule for slugs not already present — see ``_SLUG_NEW_RE``.

    Separate from the floor so the diagnosis distinguishes "this key is new and
    does not meet the convention" from "this key would corrupt the file".
    """
    if not _SLUG_NEW_RE.fullmatch(slug):
        raise MemoryBlockError(
            f"new slug {slug!r} must be kebab-case and at most 40 chars "
            "(entries already in the file are grandfathered; new ones are not)"
        )


def _parse_failure_meta(heading: str) -> tuple[str, int]:
    m = _FAILURE_META_RE.search(heading)
    if not m:
        raise MemoryBlockError(f"failure heading missing '| <date> | count:<N>': {heading!r}")
    try:
        return m.group("date"), int(m.group("count"))
    except ValueError as exc:
        raise MemoryBlockError(f"non-integer count in failure heading: {heading!r}") from exc


def _collapse_note(text: str) -> str:
    """Collapse whitespace to a single line, re-checking for markers post-collapse.

    A marker split across a newline (``<!-- @hm:user:entries\n-->``) slips past the raw
    substring guard but reforms once ``split()``/join drops the newline — guard here too.
    """
    collapsed = " ".join(text.split())
    if OPEN_MARKER in collapsed or CLOSE_MARKER in collapsed:
        raise MemoryBlockError("occurrence note contains a marker string")
    return collapsed


def _wiki_heading(category: str, slug: str, today: str) -> str:
    """Module-level single source for a wiki heading (shared by upsert + consolidate)."""
    return f"## [wiki:{category}] {slug} | {today}"


def _fail_heading(category: str, slug: str, date: str, count: int) -> str:
    """Module-level single source for a failure heading — MUST byte-match ``_FAILURE_META_RE``.

    Hoisted out of ``_upsert``'s closure so consolidate re-emits headings from the
    same builder; a drift here would break the next ``upsert-failure`` reparse.
    """
    return f"## [fail:{category}] {slug} | {date} | count:{count}"


def _entry_span_end(heading_idxs: list[int], start: int, close_idx: int) -> int:
    """End (exclusive) of the entry headed at ``start``: the next heading, else block close."""
    later = sorted(i for i in heading_idxs if i > start)
    return later[0] if later else close_idx


def _new_entry_body(
    *, is_failure: bool, body_lines: list[str], occurrence_note: str | None, today: str
) -> list[str]:
    """Body lines for a brand-new failure entry.

    Seeds from ``occurrence_note`` when no ``--body-file`` was supplied — fail-closed on
    an empty note and bullet-prefixed so a heading-shaped note can never inject a phantom
    ``## [...]`` heading. Shared by the marker-absent and no-match creation paths so both
    honor the same invariant (a ``count:N`` entry never outruns its recorded evidence).
    """
    if is_failure and occurrence_note is not None and not "".join(body_lines).strip():
        occ_text = _collapse_note(occurrence_note)
        if not occ_text:
            raise MemoryBlockError(
                "empty occurrence note on a new failure — refusing an evidence-less entry"
            )
        return [f"- [{today}] {occ_text}"]
    return body_lines


def _upsert(
    *,
    root: Path | str,
    target_file: Path,
    lock_path: Path,
    slug: str,
    body: str,
    is_failure: bool,
    category: str,
    today: str,
    title: str,
    occurrence_note: str | None = None,
) -> Path:
    # The floor runs here, outside the lock: it needs no file, and a slug that would
    # corrupt the tier must never reach a read-modify-write. The style rule cannot
    # run yet — it depends on whether this slug is already an entry heading.
    if not _SLUG_SAFE_RE.fullmatch(slug):
        raise MemoryBlockError(
            f"slug {slug!r} contains a character outside [A-Za-z0-9._-] — refused for "
            "every slug, grandfathered or not (heading reparse + unquoted shell sink)"
        )
    if not _CATEGORY_RE.fullmatch(category):
        raise MemoryBlockError(f"invalid category {category!r} (expected [a-z0-9-])")
    if OPEN_MARKER in body or CLOSE_MARKER in body:
        raise MemoryBlockError("entry body contains a marker string")
    if occurrence_note is not None and (
        OPEN_MARKER in occurrence_note or CLOSE_MARKER in occurrence_note
    ):
        raise MemoryBlockError("occurrence note contains a marker string")
    body_lines = body.strip("\n").split("\n")
    if any(_HEADING_RE.match(ln) for ln in body_lines):
        # a heading-shaped body line becomes a phantom entry on the next upsert's
        # `_entry_headings` scan → silent truncation (wiki) or tier DoS (failures).
        raise MemoryBlockError("entry body contains an entry-heading line (`## [tier:slug] …`)")

    with exclusive_lock(lock_path):
        text = target_file.read_text(encoding="utf-8") if target_file.exists() else ""
        located = _locate_block(text)

        if located is None:
            if text.strip():
                # File has real content but lost BOTH markers (corruption). Creating
                # a fresh block here would split it into unmanaged-old + managed-new
                # halves — the dedup/count history would silently vanish. Fail closed.
                raise MemoryBlockError(
                    f"{target_file} has content but no @hm:user:entries block — refusing "
                    "to split it; restore the markers manually"
                )
            # Nothing on disk yet, so the existing-heading set is empty by
            # construction — every slug reaching here is new.
            _validate_new_slug(slug)
            sys.stderr.write(
                f"[memory_md] WARN: {target_file} has no @hm:user:entries block — creating it\n"
            )
            heading = (
                _fail_heading(category, slug, today, 1)
                if is_failure
                else _wiki_heading(category, slug, today)
            )
            seed_body = _new_entry_body(
                is_failure=is_failure,
                body_lines=body_lines,
                occurrence_note=occurrence_note,
                today=today,
            )
            prefix = f"# {title} Index\n\n"
            new_text = (
                prefix
                + OPEN_MARKER
                + "\n"
                + "\n".join([heading, *seed_body])
                + "\n"
                + CLOSE_MARKER
                + "\n"
            )
            atomic_write(target_file, new_text)
            return target_file

        lines, open_idx, close_idx = located
        headings = _entry_headings(lines, open_idx, close_idx)
        # Presence is derived from the parsed HEADINGS, never from a substring scan
        # of the file: memory bodies routinely quote other entries' slugs, and a
        # `slug in text` test would grandfather a merely-mentioned key and write a
        # brand-new over-cap entry.
        if not any(s == slug for _, s in headings):
            _validate_new_slug(slug)
        matches = [idx for idx, s in headings if s == slug]
        if len(matches) > 1:
            raise MemoryBlockError(
                f"duplicate entry for slug {slug!r} — cannot pick which to replace"
            )

        if matches:
            start = matches[0]
            end = _entry_span_end([idx for idx, _ in headings], start, close_idx)
            if is_failure:
                old_date, old_count = _parse_failure_meta(lines[start])
                # occurrence-log (ADR-002): preserve the original body + prior
                # bullets, append one dated occurrence, count++. Append and
                # increment are atomic — an empty note is fail-closed so a
                # count:N entry never outruns its recorded evidence.
                source = occurrence_note if occurrence_note is not None else " ".join(body_lines)
                occ_text = _collapse_note(source)
                if not occ_text:
                    raise MemoryBlockError(
                        "empty occurrence note on a matched failure — refusing "
                        "count++ without evidence"
                    )
                heading = _fail_heading(category, slug, old_date, old_count + 1)
                existing_body = lines[start + 1 : end]
                new_lines = (
                    lines[:start]
                    + [heading, *existing_body, f"- [{today}] {occ_text}"]
                    + lines[end:]
                )
            else:
                heading = _wiki_heading(category, slug, today)
                new_lines = lines[:start] + [heading, *body_lines] + lines[end:]
        else:
            new_body = _new_entry_body(
                is_failure=is_failure,
                body_lines=body_lines,
                occurrence_note=occurrence_note,
                today=today,
            )
            heading = (
                _fail_heading(category, slug, today, 1)
                if is_failure
                else _wiki_heading(category, slug, today)
            )
            new_lines = lines[:close_idx] + [heading, *new_body] + lines[close_idx:]

        atomic_write(target_file, "\n".join(new_lines) + "\n")
    return target_file


def upsert_wiki(
    root: Path | str, slug: str, category: str, body: str, *, today: str | None = None
) -> Path:
    """Insert-or-replace a wiki entry by slug, inside the marker block, under the lock."""
    today = today or _utcnow().strftime("%Y-%m-%d")
    return _upsert(
        root=root,
        target_file=_memory_dir(root) / "wiki.md",
        lock_path=wiki_lock_path(root),
        slug=slug,
        body=body,
        is_failure=False,
        category=category,
        today=today,
        title="Wiki",
    )


def upsert_failure(
    root: Path | str,
    slug: str,
    category: str,
    body: str,
    *,
    today: str | None = None,
    occurrence_note: str | None = None,
) -> Path:
    """Insert-or-count++ a failure entry by slug, inside the marker block, under the lock.

    On a matched slug the original body is preserved and ``occurrence_note`` (or, as a
    safety net, the collapsed ``body``) is appended as a dated bullet — see ADR-002.
    """
    today = today or _utcnow().strftime("%Y-%m-%d")
    return _upsert(
        root=root,
        target_file=_memory_dir(root) / "failures.md",
        lock_path=failures_lock_path(root),
        slug=slug,
        body=body,
        is_failure=True,
        category=category,
        today=today,
        title="Failures",
        occurrence_note=occurrence_note,
    )


# ── consolidate (exact-slug duplicate merge) ─────────────────────────────────

_OCC_BULLET_RE = re.compile(r"^- \[(?P<date>\d{4}-\d{2}-\d{2})\]")
_WIKI_DATE_RE = re.compile(r"\|\s*(?P<date>\d{4}-\d{2}-\d{2})\s*$")


@dataclass(frozen=True)
class _ParsedEntry:
    idx: int
    end: int
    category: str
    slug: str
    date: str
    count: int | None  # None for wiki
    body: list[str]
    bullets: list[str]


@dataclass(frozen=True)
class ConsolidateGroup:
    """One merged exact-slug duplicate group — a report row."""

    file: str
    slug: str
    n_entries: int
    merged_count: int | None
    first_seen: str


def _strip_trailing_blank(span: list[str]) -> list[str]:
    """Drop trailing blank separator lines (inter-entry spacing) from a span."""
    end = len(span)
    while end > 0 and span[end - 1].strip() == "":
        end -= 1
    return span[:end]


def _split_body_bullets(span: list[str]) -> tuple[list[str], list[str]]:
    """Split a FAILURE entry span into (canonical_body, occurrence_bullets).

    Only a TRAILING contiguous run of ``- [YYYY-MM-DD] …`` lines counts as occurrence
    bullets; everything before is body, kept verbatim — a plain ``- item`` list line
    inside the body is NOT an occurrence bullet. Trailing blank separator lines are
    dropped first so they never mask the bullet run. Wiki entries do NOT use this —
    wiki has no occurrence-bullet convention, so its whole body (incl. any trailing
    ``- [date]`` line) stays body (P0 fix: peeling bullets off a wiki entry that the
    wiki merge never re-emits would silently drop those lines).
    """
    core = _strip_trailing_blank(span)
    b = len(core)
    while b > 0 and _OCC_BULLET_RE.match(core[b - 1]):
        b -= 1
    return core[:b], core[b:]


def _parse_entries(
    lines: list[str], open_idx: int, close_idx: int, *, is_failure: bool
) -> list[_ParsedEntry]:
    heads = [
        (i, m)
        for i in range(open_idx + 1, close_idx)
        if (m := _HEADING_RE.match(lines[i])) is not None
    ]
    idxs = [i for i, _ in heads]
    out: list[_ParsedEntry] = []
    for i, m in heads:
        end = _entry_span_end(idxs, i, close_idx)
        span = lines[i + 1 : end]
        date = ""
        cnt: int | None = None
        if is_failure:
            body, bullets = _split_body_bullets(span)
            # Tolerant: a legacy/hand-edited heading (e.g. a trailing `| previous_count:N`
            # that fails `_FAILURE_META_RE`) is fine for a SINGLETON — it is copied
            # verbatim and its count is never read. A dup-group member with unparseable
            # meta is rejected in `_consolidate_file` (can't merge what we can't parse).
            try:
                date, cnt = _parse_failure_meta(lines[i])
            except MemoryBlockError:
                date, cnt = "", None
        else:
            # Wiki: no occurrence-bullet convention — the WHOLE body (including a
            # trailing `- [date]` line) is body; bullets is always empty (P0 fix).
            body, bullets = _strip_trailing_blank(span), []
            dm = _WIKI_DATE_RE.search(lines[i])
            date = dm.group("date") if dm else ""
        out.append(_ParsedEntry(i, end, m.group("cat"), m.group("slug"), date, cnt, body, bullets))
    return out


def _bullet_sort_key(bullet: str) -> str:
    m = _OCC_BULLET_RE.match(bullet)
    return m.group("date") if m else ""


def _merge_group(members: list[_ParsedEntry], *, is_failure: bool, today: str) -> list[str]:
    """Merge one exact-slug group into a single entry's lines (heading + body + trailer)."""
    # An undated member (empty date — only reachable for wiki; failures reject it) sorts
    # LAST so a real-dated member becomes canonical and carries the real first-seen date.
    members = sorted(members, key=lambda e: e.date or "9999-99-99")
    canonical = members[0]
    cats = {m.category for m in members}
    if is_failure:
        counts = [m.count if m.count is not None else 0 for m in members]
        merged_count = sum(counts)
        bullets: list[str] = []
        for m in members:
            bullets.extend(m.bullets)
        for m in members[1:]:
            folded = _collapse_note(" ".join(m.body))  # raises on a marker string → all-or-nothing
            if folded:
                bullets.append(f"- [{m.date}] {folded}")
        note = (
            f"consolidated {len(members)} duplicate entries "
            f"(counts {'+'.join(str(c) for c in counts)} = {merged_count})"
        )
        if len(cats) > 1:
            note += f"; mixed categories {sorted(cats)}, kept {canonical.category!r}"
        bullets.append(f"- [{today}] {note}")
        bullets.sort(key=_bullet_sort_key)  # stable → chronological
        heading = _fail_heading(canonical.category, canonical.slug, canonical.date, merged_count)
        return [heading, *canonical.body, *bullets, ""]

    # wiki — no count, no bullets: concatenate later bodies into the canonical paragraph
    body = list(canonical.body)
    for m in members[1:]:
        if any(ln.strip() for ln in m.body):
            body.extend(["", *m.body])
    if len(cats) > 1:
        body.extend(
            ["", f"(consolidated: mixed categories {sorted(cats)}, kept {canonical.category!r})"]
        )
    # `canonical.date or today`: a dateless wiki dup member would otherwise render a
    # dangling `## [wiki:cat] slug | ` trailer (Codex/code-reviewer finding).
    heading = _wiki_heading(canonical.category, canonical.slug, canonical.date or today)
    return [heading, *body, ""]


def _consolidate_file(
    target_file: Path,
    lock_path: Path,
    *,
    file_label: str,
    is_failure: bool,
    today: str,
    dry_run: bool,
) -> list[ConsolidateGroup]:
    with exclusive_lock(lock_path):
        if not target_file.exists():
            return []
        located = _locate_block(target_file.read_text(encoding="utf-8"))
        if located is None:
            return []
        lines, open_idx, close_idx = located
        entries = _parse_entries(lines, open_idx, close_idx, is_failure=is_failure)
        order: list[str] = []
        by_slug: dict[str, list[_ParsedEntry]] = {}
        for e in entries:
            by_slug.setdefault(e.slug, [])
            if len(by_slug[e.slug]) == 0:
                order.append(e.slug)
            by_slug[e.slug].append(e)
        dup_slugs = [s for s in order if len(by_slug[s]) > 1]
        if not dup_slugs:
            return []  # no exact dups → byte-identical no-op (never writes)

        # A dup-group member must have clean, parseable meta to merge safely (a
        # singleton with legacy meta is tolerated — it is copied verbatim, not merged).
        if is_failure:
            for s in dup_slugs:
                bad = [m for m in by_slug[s] if m.count is None or not m.date]
                if bad:
                    raise MemoryBlockError(
                        f"duplicate slug {s!r} has an unparseable failure heading "
                        f"(line {bad[0].idx + 1}) — fix its `| <date> | count:<N>` meta first"
                    )

        # Rebuild the entries region: singleton spans verbatim, dup groups merged at
        # the earliest member's position. _merge_group may raise (marker fold) BEFORE
        # any write → all-or-nothing.
        region: list[str] = list(lines[open_idx + 1 : entries[0].idx])
        for slug in order:
            members = by_slug[slug]
            if len(members) == 1:
                e = members[0]
                region.extend(lines[e.idx : e.end])
            else:
                region.extend(_merge_group(members, is_failure=is_failure, today=today))
        new_lines = lines[: open_idx + 1] + region + lines[close_idx:]

        groups = [
            ConsolidateGroup(
                file=file_label,
                slug=s,
                n_entries=len(by_slug[s]),
                merged_count=(sum((m.count or 0) for m in by_slug[s]) if is_failure else None),
                # ignore undated (empty) members so first_seen matches the real canonical date
                first_seen=min((m.date for m in by_slug[s] if m.date), default=""),
            )
            for s in dup_slugs
        ]
        if not dry_run:
            atomic_write(target_file, "\n".join(new_lines) + "\n")
        return groups


def consolidate(
    root: Path | str,
    *,
    which: str = "both",
    dry_run: bool = False,
    today: str | None = None,
) -> list[ConsolidateGroup]:
    """Merge exact-slug duplicate entries in the failures/wiki tiers under the lock.

    Opt-in maintenance (never wrapup-auto). Failures: count=sum, earliest body
    canonical, later bodies fold to dated occurrence bullets, all-or-nothing on a
    marker-string fold. Wiki: bodies concatenate. The no-dup case never writes.

    All-or-nothing is **per file**: with ``which="both"`` failures is processed
    first, so an OSError on the wiki write (after failures already wrote) leaves
    failures.md updated + wiki.md unchanged. Each file is individually consistent
    (atomic_write); there is no cross-file transaction.
    """
    today = today or _utcnow().strftime("%Y-%m-%d")
    md = _memory_dir(root)
    targets: list[tuple[str, Path, Path, bool]] = []
    if which in ("failures", "both"):
        targets.append(("failures", md / "failures.md", failures_lock_path(root), True))
    if which in ("wiki", "both"):
        targets.append(("wiki", md / "wiki.md", wiki_lock_path(root), False))
    if not targets:
        raise MemoryBlockError(f"invalid --file {which!r} (expected failures|wiki|both)")
    out: list[ConsolidateGroup] = []
    for label, target, lock, is_fail in targets:
        out.extend(
            _consolidate_file(
                target, lock, file_label=label, is_failure=is_fail, today=today, dry_run=dry_run
            )
        )
    return out


# ── CLI ──────────────────────────────────────────────────────────────────────


def _read_body(args: argparse.Namespace) -> str:
    if args.body is not None:
        return str(args.body)
    if args.body_file is not None:
        return Path(args.body_file).read_text(encoding="utf-8")
    return sys.stdin.read()


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python -m harness_maker.memory_md",
        description="Concurrency-safe (flock) writes to the markdown memory tiers.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    def _common(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--root", default=".", type=Path)
        sp.add_argument("--body", default=None, help="Entry body (prefer --body-file/stdin).")
        sp.add_argument("--body-file", default=None, help="Path to a file holding the entry body.")
        sp.add_argument("--today", default=None, help="YYYY-MM-DD (deterministic date).")

    a = sub.add_parser("append-session", help="Append an entry to today's session log.")
    _common(a)

    w = sub.add_parser("upsert-wiki", help="Insert-or-replace a wiki entry by slug.")
    _common(w)
    w.add_argument("--slug", required=True)
    w.add_argument("--category", required=True)

    f = sub.add_parser("upsert-failure", help="Insert-or-count++ a failure entry by slug.")
    _common(f)
    f.add_argument("--slug", required=True)
    f.add_argument("--category", required=True)
    f.add_argument(
        "--occurrence-note",
        default=None,
        help="On a matched slug, append this one-line dated occurrence (count++).",
    )

    c = sub.add_parser(
        "consolidate", help="Merge exact-slug duplicate entries (opt-in maintenance)."
    )
    c.add_argument("--root", default=".", type=Path)
    c.add_argument("--file", choices=("failures", "wiki", "both"), default="both", dest="which")
    c.add_argument("--today", default=None, help="YYYY-MM-DD (deterministic date).")
    c.add_argument("--dry-run", action="store_true")

    return p


def main(argv: list[str] | None = None) -> int:
    _guard = command_registry.guard_or_none("memory_md", argv)
    if _guard is not None:
        return _guard
    args = _build_parser().parse_args(argv)
    try:
        if args.cmd == "consolidate":
            groups = consolidate(
                args.root, which=args.which, dry_run=args.dry_run, today=args.today
            )
            for g in groups:
                meta = f"count:{g.merged_count}, " if g.merged_count is not None else ""
                sys.stdout.write(
                    f"{g.file} {g.slug}: {g.n_entries} entries -> {meta}first-seen {g.first_seen}\n"
                )
            collapsed = sum(g.n_entries for g in groups) - len(groups)
            tail = " (dry-run)" if args.dry_run else ""
            sys.stdout.write(
                f"consolidate: {len(groups)} group(s), {collapsed} entries collapsed{tail}\n"
            )
            return 0
        # For upsert-failure with --occurrence-note, the note is the payload — do
        # NOT read stdin (that would block when no body/--body-file is supplied).
        occ = getattr(args, "occurrence_note", None)
        if occ is not None and (args.body is not None or args.body_file is not None):
            # Mutually exclusive: silently dropping the richer body is a footgun.
            raise MemoryBlockError(
                "--occurrence-note is mutually exclusive with --body/--body-file"
            )
        body = "" if (args.cmd == "upsert-failure" and occ is not None) else _read_body(args)
        if args.cmd == "append-session":
            path = append_session(args.root, body, today=args.today)
        elif args.cmd == "upsert-wiki":
            path = upsert_wiki(args.root, args.slug, args.category, body, today=args.today)
        elif args.cmd == "upsert-failure":
            path = upsert_failure(
                args.root, args.slug, args.category, body, today=args.today, occurrence_note=occ
            )
        else:  # pragma: no cover — argparse enforces a valid subcommand
            return 2
    except (MemoryBlockError, OSError, ValueError) as exc:
        sys.stderr.write(f"{args.cmd} failed: {exc}\n")
        return 1
    sys.stdout.write(str(path) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
