"""PreCompact flush hook — snapshot autoloop progress before context compaction.

Why: .claude-progress.json is only written at stage wrapup boundaries. When
Claude Code auto-compacts mid-stage, partial work (tasks completed so far,
review findings in flight, research notes) evaporates. This hook fires before
every compaction (auto + manual), snapshots the progress file, and appends a
checkpoint entry to the session log so the next context window knows where the
session was interrupted.
"""

from __future__ import annotations

import json
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

_PROGRESS_FILE = ".claude-progress.json"
_CHECKPOINT_PREFIX = ".claude-progress-checkpoint-"
_SESSION_DIR = Path(".claude") / "memory" / "session"


def _utcnow() -> datetime:
    return datetime.now(tz=UTC)


def _read_stdin() -> dict[str, Any]:
    try:
        raw = sys.stdin.read()
        data = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        data = {}
    return data if isinstance(data, dict) else {}


def _snapshot_progress(cwd: Path, ts: str) -> Path | None:
    """Copy .claude-progress.json to a timestamped checkpoint. Returns dest path or None."""
    src = cwd / _PROGRESS_FILE
    if not src.exists():
        return None
    dest = cwd / f"{_CHECKPOINT_PREFIX}{ts}.json"
    shutil.copy2(src, dest)
    return dest


def _append_session_log(cwd: Path, ts: str, trigger: str, checkpoint: Path | None) -> None:
    """Append a compaction checkpoint entry to today's session log."""
    session_dir = cwd / _SESSION_DIR
    session_dir.mkdir(parents=True, exist_ok=True)
    today = _utcnow().strftime("%Y-%m-%d")
    log_file = session_dir / f"{today}.md"

    checkpoint_ref = checkpoint.name if checkpoint else "no progress file"
    entry = (
        f"\n## [checkpoint:compaction] autocompact-{ts[:16].replace('T', '-')} "
        f"| {ts[:19].replace('T', ' ')} UTC | trigger:{trigger}\n"
        f"Context compaction fired. Progress snapshotted to `{checkpoint_ref}`.\n"
        f"Resume: load `.claude-progress.json` and continue from `current_phase`.\n"
    )

    if not log_file.exists():
        header = (
            f"# Session Log — {today}\n\n"
            f"> Auto-generated by harness-maker flush_session hook.\n"
            f"> Format: `## [category:slug] description | HH:MM UTC | stage:name`\n\n"
        )
        log_file.write_text(header + entry, encoding="utf-8")
    else:
        with log_file.open("a", encoding="utf-8") as f:
            f.write(entry)


def run(cwd: Path | None = None) -> int:
    """Main logic — separated for testability."""
    if cwd is None:
        cwd = Path.cwd()

    payload = _read_stdin()
    trigger = str(payload.get("trigger", "unknown"))
    ts = _utcnow().strftime("%Y%m%dT%H%M%SZ")

    checkpoint = _snapshot_progress(cwd, ts)
    _append_session_log(cwd, ts, trigger, checkpoint)
    return 0


def main() -> int:
    """Entry point: called by PreCompact hook in hooks.json."""
    return run()


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
