"""Tests for block_merge — marker parsing + 3-way merge of user blocks."""

from __future__ import annotations

import hashlib

import pytest

from harness_maker.block_merge import (
    BlockKind,
    ParseError,
    block_hashes,
    detect_drift,
    has_markers,
    merge,
    parse_segments,
    parse_user_blocks,
)

# ──────────────────────────────────────────────────────────────────────────────
# has_markers
# ──────────────────────────────────────────────────────────────────────────────


def test_has_markers_detects_user_block() -> None:
    text = "intro\n<!-- @hm:user:notes -->\nx\n<!-- @hm:/user:notes -->\n"
    assert has_markers(text)


def test_has_markers_detects_template_block() -> None:
    text = "<!-- @hm:block:procedure -->\n1.\n<!-- @hm:/block:procedure -->\n"
    assert has_markers(text)


def test_has_markers_negative_on_plain_markdown() -> None:
    assert not has_markers("# Heading\n\nplain content\n")


def test_has_markers_negative_on_unrelated_html_comment() -> None:
    assert not has_markers("<!-- generated by foo -->\nbody\n")


# ──────────────────────────────────────────────────────────────────────────────
# parse_segments
# ──────────────────────────────────────────────────────────────────────────────


def test_parse_segments_extracts_user_block_body() -> None:
    text = "pre\n<!-- @hm:user:notes -->\nline1\nline2\n<!-- @hm:/user:notes -->\npost\n"
    segs = parse_segments(text)
    assert len(segs) == 1
    assert segs[0].kind == BlockKind.USER
    assert segs[0].id == "notes"
    assert segs[0].content == "line1\nline2\n"


def test_parse_segments_handles_multiple_blocks_in_order() -> None:
    text = (
        "<!-- @hm:block:a -->\nA\n<!-- @hm:/block:a -->\n"
        "<!-- @hm:user:b -->\nB\n<!-- @hm:/user:b -->\n"
    )
    segs = parse_segments(text)
    assert [(s.kind, s.id) for s in segs] == [(BlockKind.BLOCK, "a"), (BlockKind.USER, "b")]


def test_parse_segments_empty_block() -> None:
    text = "<!-- @hm:user:empty -->\n<!-- @hm:/user:empty -->\n"
    segs = parse_segments(text)
    assert segs[0].content == ""


def test_parse_segments_rejects_unmatched_close() -> None:
    text = "intro\n<!-- @hm:/user:nope -->\n"
    with pytest.raises(ParseError, match="Unmatched close marker"):
        parse_segments(text)


def test_parse_segments_rejects_unclosed_open() -> None:
    text = "<!-- @hm:user:dangling -->\nbody\n"
    with pytest.raises(ParseError, match="Unclosed marker"):
        parse_segments(text)


def test_parse_segments_rejects_close_id_mismatch() -> None:
    text = "<!-- @hm:user:foo -->\n<!-- @hm:/user:bar -->\n"
    with pytest.raises(ParseError, match="Marker mismatch"):
        parse_segments(text)


def test_parse_segments_rejects_close_kind_mismatch() -> None:
    text = "<!-- @hm:user:foo -->\n<!-- @hm:/block:foo -->\n"
    with pytest.raises(ParseError, match="Marker mismatch"):
        parse_segments(text)


def test_parse_segments_rejects_duplicate_id() -> None:
    text = (
        "<!-- @hm:user:foo -->\nA\n<!-- @hm:/user:foo -->\n"
        "<!-- @hm:user:foo -->\nB\n<!-- @hm:/user:foo -->\n"
    )
    with pytest.raises(ParseError, match="Duplicate marker id"):
        parse_segments(text)


def test_parse_segments_rejects_nested_marker() -> None:
    text = (
        "<!-- @hm:user:outer -->\n"
        "<!-- @hm:user:inner -->\nx\n<!-- @hm:/user:inner -->\n"
        "<!-- @hm:/user:outer -->\n"
    )
    with pytest.raises(ParseError, match="Nested marker"):
        parse_segments(text)


def test_parse_segments_underscore_prefixed_id_allowed() -> None:
    """`_orphans` is a system-emitted id and must parse cleanly."""
    text = "<!-- @hm:user:_orphans -->\nbody\n<!-- @hm:/user:_orphans -->\n"
    segs = parse_segments(text)
    assert segs[0].id == "_orphans"


def test_parse_segments_tolerates_indented_markers() -> None:
    text = "  <!-- @hm:user:a -->\n  body\n  <!-- @hm:/user:a -->\n"
    segs = parse_segments(text)
    assert segs[0].id == "a"
    assert segs[0].content == "  body\n"


# ──────────────────────────────────────────────────────────────────────────────
# parse_user_blocks / block_hashes / detect_drift
# ──────────────────────────────────────────────────────────────────────────────


def test_parse_user_blocks_only_user_kind() -> None:
    text = (
        "<!-- @hm:block:rubric -->\nR\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\nN\n<!-- @hm:/user:notes -->\n"
    )
    assert parse_user_blocks(text) == {"notes": "N\n"}


def test_block_hashes_only_block_kind() -> None:
    text = (
        "<!-- @hm:block:rubric -->\nR\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\nN\n<!-- @hm:/user:notes -->\n"
    )
    expected = hashlib.sha256(b"R\n").hexdigest()
    assert block_hashes(text) == {"rubric": expected}


def test_detect_drift_flags_edited_block() -> None:
    text = "<!-- @hm:block:rubric -->\nedited\n<!-- @hm:/block:rubric -->\n"
    recorded = {"rubric": hashlib.sha256(b"original\n").hexdigest()}
    assert detect_drift(text, recorded) == ["rubric"]


def test_detect_drift_clean_when_hashes_match() -> None:
    text = "<!-- @hm:block:rubric -->\nbody\n<!-- @hm:/block:rubric -->\n"
    recorded = {"rubric": hashlib.sha256(b"body\n").hexdigest()}
    assert detect_drift(text, recorded) == []


def test_detect_drift_ignores_unknown_recorded_id() -> None:
    """Recorded hash for an id no longer in the file — not drift, just absent."""
    text = "<!-- @hm:block:a -->\nA\n<!-- @hm:/block:a -->\n"
    recorded = {"removed": "deadbeef"}
    assert detect_drift(text, recorded) == []


# ──────────────────────────────────────────────────────────────────────────────
# merge
# ──────────────────────────────────────────────────────────────────────────────


def test_merge_preserves_user_block_content() -> None:
    old = (
        "header\n"
        "<!-- @hm:user:notes -->\n"
        "my custom step\n"
        "<!-- @hm:/user:notes -->\n"
    )
    new = (
        "header v2\n"  # template structure changed
        "<!-- @hm:user:notes -->\n"
        "(seed placeholder)\n"
        "<!-- @hm:/user:notes -->\n"
    )
    merged, report = merge(old, new)
    assert "header v2" in merged
    assert "my custom step" in merged
    assert "(seed placeholder)" not in merged
    assert report.user_blocks_preserved == ["notes"]
    assert report.user_blocks_seeded == []
    assert report.user_blocks_orphaned == []


def test_merge_seeds_new_user_block_when_old_missing() -> None:
    old = "header\n"  # no markers in OLD
    new = (
        "header\n"
        "<!-- @hm:user:notes -->\n"
        "(seed)\n"
        "<!-- @hm:/user:notes -->\n"
    )
    merged, report = merge(old, new)
    assert "(seed)" in merged
    assert report.user_blocks_seeded == ["notes"]
    assert report.user_blocks_preserved == []


def test_merge_orphans_old_user_block_absent_from_new() -> None:
    old = (
        "header\n"
        "<!-- @hm:user:legacy -->\n"
        "important user content\n"
        "<!-- @hm:/user:legacy -->\n"
    )
    new = "header v2\n"  # no user blocks
    merged, report = merge(old, new)
    assert "important user content" in merged
    assert "@hm:user:_orphans" in merged
    assert "(orphan) legacy" in merged
    assert report.user_blocks_orphaned == ["legacy"]


def test_merge_replaces_template_content_outside_markers() -> None:
    old = (
        "old template body\n"
        "<!-- @hm:user:notes -->\n"
        "user note\n"
        "<!-- @hm:/user:notes -->\n"
    )
    new = (
        "new template body with grade gate\n"
        "<!-- @hm:user:notes -->\n"
        "(seed)\n"
        "<!-- @hm:/user:notes -->\n"
    )
    merged, _ = merge(old, new)
    assert "new template body with grade gate" in merged
    assert "old template body" not in merged
    assert "user note" in merged


def test_merge_idempotent_when_no_user_edits() -> None:
    """If OLD has user block with seed content and NEW has the same seed,
    merging produces the same file (modulo whitespace).
    """
    text = (
        "header\n"
        "<!-- @hm:user:notes -->\n"
        "(seed)\n"
        "<!-- @hm:/user:notes -->\n"
    )
    merged, report = merge(text, text)
    assert merged == text
    assert report.user_blocks_preserved == ["notes"]


def test_merge_handles_multiple_user_blocks() -> None:
    old = (
        "<!-- @hm:user:a -->\nAAA\n<!-- @hm:/user:a -->\n"
        "<!-- @hm:user:b -->\nBBB\n<!-- @hm:/user:b -->\n"
    )
    new = (
        "<!-- @hm:user:a -->\n(seed-a)\n<!-- @hm:/user:a -->\n"
        "<!-- @hm:user:b -->\n(seed-b)\n<!-- @hm:/user:b -->\n"
    )
    merged, report = merge(old, new)
    assert "AAA" in merged
    assert "BBB" in merged
    assert "(seed-a)" not in merged
    assert "(seed-b)" not in merged
    assert sorted(report.user_blocks_preserved) == ["a", "b"]


def test_merge_preserves_empty_user_block() -> None:
    old = "<!-- @hm:user:notes -->\n<!-- @hm:/user:notes -->\n"
    new = "<!-- @hm:user:notes -->\n(seed)\n<!-- @hm:/user:notes -->\n"
    merged, report = merge(old, new)
    # Empty OLD body means the merged user region is also empty.
    assert "(seed)" not in merged
    assert report.user_blocks_preserved == ["notes"]


def test_merge_block_template_content_taken_from_new() -> None:
    """`block:<id>` in OLD is discarded — NEW always wins for template-owned regions."""
    old = (
        "<!-- @hm:block:rubric -->\nold rubric (user-edited)\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\nuser content\n<!-- @hm:/user:notes -->\n"
    )
    new = (
        "<!-- @hm:block:rubric -->\nnew rubric\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\n(seed)\n<!-- @hm:/user:notes -->\n"
    )
    merged, _ = merge(old, new)
    assert "new rubric" in merged
    assert "old rubric" not in merged
    assert "user content" in merged


def test_merge_raises_on_malformed_old() -> None:
    old = "<!-- @hm:user:dangling -->\nbody\n"  # unclosed
    new = "<!-- @hm:user:dangling -->\n(seed)\n<!-- @hm:/user:dangling -->\n"
    with pytest.raises(ParseError):
        merge(old, new)


def test_merge_raises_on_malformed_new() -> None:
    old = "<!-- @hm:user:notes -->\nuser\n<!-- @hm:/user:notes -->\n"
    new = "<!-- @hm:user:notes -->\nseed\n"  # unclosed
    with pytest.raises(ParseError):
        merge(old, new)
