"""Tests for block_merge — marker parsing + 3-way merge of user blocks."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from harness_maker.block_merge import (
    BlockKind,
    MarkerMismatchError,
    MarkerNestedError,
    MarkerStyle,
    ParseError,
    block_hashes,
    detect_drift,
    detect_marker_style,
    has_markers,
    merge,
    merge_inverted,
    parse_harness_blocks,
    parse_segments,
    parse_user_blocks,
)

# ──────────────────────────────────────────────────────────────────────────────
# has_markers
# ──────────────────────────────────────────────────────────────────────────────


def test_has_markers_detects_user_block() -> None:
    text = "intro\n<!-- @hm:user:notes -->\nx\n<!-- @hm:/user:notes -->\n"
    assert has_markers(text)


def test_has_markers_detects_template_block() -> None:
    text = "<!-- @hm:block:procedure -->\n1.\n<!-- @hm:/block:procedure -->\n"
    assert has_markers(text)


def test_has_markers_negative_on_plain_markdown() -> None:
    assert not has_markers("# Heading\n\nplain content\n")


def test_has_markers_negative_on_unrelated_html_comment() -> None:
    assert not has_markers("<!-- generated by foo -->\nbody\n")


# ──────────────────────────────────────────────────────────────────────────────
# parse_segments
# ──────────────────────────────────────────────────────────────────────────────


def test_parse_segments_extracts_user_block_body() -> None:
    text = "pre\n<!-- @hm:user:notes -->\nline1\nline2\n<!-- @hm:/user:notes -->\npost\n"
    segs = parse_segments(text)
    assert len(segs) == 1
    assert segs[0].kind == BlockKind.USER
    assert segs[0].id == "notes"
    assert segs[0].content == "line1\nline2\n"


def test_parse_segments_handles_multiple_blocks_in_order() -> None:
    text = (
        "<!-- @hm:block:a -->\nA\n<!-- @hm:/block:a -->\n"
        "<!-- @hm:user:b -->\nB\n<!-- @hm:/user:b -->\n"
    )
    segs = parse_segments(text)
    assert [(s.kind, s.id) for s in segs] == [(BlockKind.BLOCK, "a"), (BlockKind.USER, "b")]


def test_parse_segments_empty_block() -> None:
    text = "<!-- @hm:user:empty -->\n<!-- @hm:/user:empty -->\n"
    segs = parse_segments(text)
    assert segs[0].content == ""


def test_parse_segments_rejects_unmatched_close() -> None:
    text = "intro\n<!-- @hm:/user:nope -->\n"
    with pytest.raises(ParseError, match="Unmatched close marker"):
        parse_segments(text)


def test_parse_segments_rejects_unclosed_open() -> None:
    text = "<!-- @hm:user:dangling -->\nbody\n"
    with pytest.raises(ParseError, match="Unclosed marker"):
        parse_segments(text)


def test_parse_segments_rejects_close_id_mismatch() -> None:
    text = "<!-- @hm:user:foo -->\n<!-- @hm:/user:bar -->\n"
    with pytest.raises(ParseError, match="Marker mismatch"):
        parse_segments(text)


def test_parse_segments_rejects_close_kind_mismatch() -> None:
    text = "<!-- @hm:user:foo -->\n<!-- @hm:/block:foo -->\n"
    with pytest.raises(ParseError, match="Marker mismatch"):
        parse_segments(text)


def test_parse_segments_rejects_duplicate_id() -> None:
    text = (
        "<!-- @hm:user:foo -->\nA\n<!-- @hm:/user:foo -->\n"
        "<!-- @hm:user:foo -->\nB\n<!-- @hm:/user:foo -->\n"
    )
    with pytest.raises(ParseError, match="Duplicate marker id"):
        parse_segments(text)


def test_parse_segments_rejects_nested_marker() -> None:
    text = (
        "<!-- @hm:user:outer -->\n"
        "<!-- @hm:user:inner -->\nx\n<!-- @hm:/user:inner -->\n"
        "<!-- @hm:/user:outer -->\n"
    )
    with pytest.raises(ParseError, match="Nested marker"):
        parse_segments(text)


def test_parse_segments_underscore_prefixed_id_allowed() -> None:
    """`_orphans` is a system-emitted id and must parse cleanly."""
    text = "<!-- @hm:user:_orphans -->\nbody\n<!-- @hm:/user:_orphans -->\n"
    segs = parse_segments(text)
    assert segs[0].id == "_orphans"


def test_parse_segments_tolerates_indented_markers() -> None:
    text = "  <!-- @hm:user:a -->\n  body\n  <!-- @hm:/user:a -->\n"
    segs = parse_segments(text)
    assert segs[0].id == "a"
    assert segs[0].content == "  body\n"


# ──────────────────────────────────────────────────────────────────────────────
# parse_user_blocks / block_hashes / detect_drift
# ──────────────────────────────────────────────────────────────────────────────


def test_parse_user_blocks_only_user_kind() -> None:
    text = (
        "<!-- @hm:block:rubric -->\nR\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\nN\n<!-- @hm:/user:notes -->\n"
    )
    assert parse_user_blocks(text) == {"notes": "N\n"}


def test_block_hashes_only_block_kind() -> None:
    text = (
        "<!-- @hm:block:rubric -->\nR\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\nN\n<!-- @hm:/user:notes -->\n"
    )
    expected = hashlib.sha256(b"R\n").hexdigest()
    assert block_hashes(text) == {"rubric": expected}


def test_detect_drift_flags_edited_block() -> None:
    text = "<!-- @hm:block:rubric -->\nedited\n<!-- @hm:/block:rubric -->\n"
    recorded = {"rubric": hashlib.sha256(b"original\n").hexdigest()}
    assert detect_drift(text, recorded) == ["rubric"]


def test_detect_drift_clean_when_hashes_match() -> None:
    text = "<!-- @hm:block:rubric -->\nbody\n<!-- @hm:/block:rubric -->\n"
    recorded = {"rubric": hashlib.sha256(b"body\n").hexdigest()}
    assert detect_drift(text, recorded) == []


def test_detect_drift_ignores_unknown_recorded_id() -> None:
    """Recorded hash for an id no longer in the file — not drift, just absent."""
    text = "<!-- @hm:block:a -->\nA\n<!-- @hm:/block:a -->\n"
    recorded = {"removed": "deadbeef"}
    assert detect_drift(text, recorded) == []


# ──────────────────────────────────────────────────────────────────────────────
# merge
# ──────────────────────────────────────────────────────────────────────────────


def test_merge_preserves_user_block_content() -> None:
    old = "header\n<!-- @hm:user:notes -->\nmy custom step\n<!-- @hm:/user:notes -->\n"
    new = (
        "header v2\n"  # template structure changed
        "<!-- @hm:user:notes -->\n"
        "(seed placeholder)\n"
        "<!-- @hm:/user:notes -->\n"
    )
    merged, report = merge(old, new)
    assert "header v2" in merged
    assert "my custom step" in merged
    assert "(seed placeholder)" not in merged
    assert report.user_blocks_preserved == ["notes"]
    assert report.user_blocks_seeded == []
    assert report.user_blocks_orphaned == []


def test_merge_seeds_new_user_block_when_old_missing() -> None:
    old = "header\n"  # no markers in OLD
    new = "header\n<!-- @hm:user:notes -->\n(seed)\n<!-- @hm:/user:notes -->\n"
    merged, report = merge(old, new)
    assert "(seed)" in merged
    assert report.user_blocks_seeded == ["notes"]
    assert report.user_blocks_preserved == []


def test_merge_orphans_old_user_block_absent_from_new() -> None:
    old = "header\n<!-- @hm:user:legacy -->\nimportant user content\n<!-- @hm:/user:legacy -->\n"
    new = "header v2\n"  # no user blocks
    merged, report = merge(old, new)
    assert "important user content" in merged
    assert "@hm:user:_orphans" in merged
    assert "(orphan) legacy" in merged
    assert report.user_blocks_orphaned == ["legacy"]


def test_merge_replaces_template_content_outside_markers() -> None:
    old = "old template body\n<!-- @hm:user:notes -->\nuser note\n<!-- @hm:/user:notes -->\n"
    new = (
        "new template body with grade gate\n"
        "<!-- @hm:user:notes -->\n"
        "(seed)\n"
        "<!-- @hm:/user:notes -->\n"
    )
    merged, _ = merge(old, new)
    assert "new template body with grade gate" in merged
    assert "old template body" not in merged
    assert "user note" in merged


def test_merge_idempotent_when_no_user_edits() -> None:
    """If OLD has user block with seed content and NEW has the same seed,
    merging produces the same file (modulo whitespace).
    """
    text = "header\n<!-- @hm:user:notes -->\n(seed)\n<!-- @hm:/user:notes -->\n"
    merged, report = merge(text, text)
    assert merged == text
    assert report.user_blocks_preserved == ["notes"]


def test_merge_handles_multiple_user_blocks() -> None:
    old = (
        "<!-- @hm:user:a -->\nAAA\n<!-- @hm:/user:a -->\n"
        "<!-- @hm:user:b -->\nBBB\n<!-- @hm:/user:b -->\n"
    )
    new = (
        "<!-- @hm:user:a -->\n(seed-a)\n<!-- @hm:/user:a -->\n"
        "<!-- @hm:user:b -->\n(seed-b)\n<!-- @hm:/user:b -->\n"
    )
    merged, report = merge(old, new)
    assert "AAA" in merged
    assert "BBB" in merged
    assert "(seed-a)" not in merged
    assert "(seed-b)" not in merged
    assert sorted(report.user_blocks_preserved) == ["a", "b"]


def test_merge_preserves_empty_user_block() -> None:
    old = "<!-- @hm:user:notes -->\n<!-- @hm:/user:notes -->\n"
    new = "<!-- @hm:user:notes -->\n(seed)\n<!-- @hm:/user:notes -->\n"
    merged, report = merge(old, new)
    # Empty OLD body means the merged user region is also empty.
    assert "(seed)" not in merged
    assert report.user_blocks_preserved == ["notes"]


def test_merge_block_template_content_taken_from_new() -> None:
    """`block:<id>` in OLD is discarded — NEW always wins for template-owned regions."""
    old = (
        "<!-- @hm:block:rubric -->\nold rubric (user-edited)\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\nuser content\n<!-- @hm:/user:notes -->\n"
    )
    new = (
        "<!-- @hm:block:rubric -->\nnew rubric\n<!-- @hm:/block:rubric -->\n"
        "<!-- @hm:user:notes -->\n(seed)\n<!-- @hm:/user:notes -->\n"
    )
    merged, _ = merge(old, new)
    assert "new rubric" in merged
    assert "old rubric" not in merged
    assert "user content" in merged


def test_merge_raises_on_malformed_old() -> None:
    old = "<!-- @hm:user:dangling -->\nbody\n"  # unclosed
    new = "<!-- @hm:user:dangling -->\n(seed)\n<!-- @hm:/user:dangling -->\n"
    with pytest.raises(ParseError):
        merge(old, new)


def test_merge_raises_on_malformed_new() -> None:
    old = "<!-- @hm:user:notes -->\nuser\n<!-- @hm:/user:notes -->\n"
    new = "<!-- @hm:user:notes -->\nseed\n"  # unclosed
    with pytest.raises(ParseError):
        merge(old, new)


# ──────────────────────────────────────────────────────────────────────────────
# Phase 6 — @hm:harness:* family (ADR-009 inverted markers)
# Validator W2: 6 marker test cases enumerated below.
# ──────────────────────────────────────────────────────────────────────────────


def test_only_user_markers_unchanged_after_parse() -> None:
    """W2 regression baseline — existing @hm:user:* corpus byte-for-byte
    zero-churn. Adding the harness family must not perturb the user family.
    """
    corpus = (
        "# header\n"
        "<!-- @hm:user:notes -->\n"
        "user content stays here verbatim\n"
        "<!-- @hm:/user:notes -->\n"
        "<!-- @hm:block:rubric -->\n"
        "template body\n"
        "<!-- @hm:/block:rubric -->\n"
    )
    segs = parse_segments(corpus)
    assert [(s.kind, s.id, s.content) for s in segs] == [
        (BlockKind.USER, "notes", "user content stays here verbatim\n"),
        (BlockKind.BLOCK, "rubric", "template body\n"),
    ]
    # merge(corpus, corpus) — idempotent zero-churn on the user family alone.
    merged, report = merge(corpus, corpus)
    assert merged == corpus
    assert report.user_blocks_preserved == ["notes"]


def test_only_harness_markers_inverted_semantics() -> None:
    """W2 — harness family ONLY: outside-marker user prose preserved
    byte-for-byte; inside-marker body replaced from NEW.
    """
    user_owns = (
        "# My CLAUDE.md\n"
        "\n"
        "This is my custom project description. The harness only manages the\n"
        "metadata block below; everything else is mine.\n"
        "\n"
        "<!-- @hm:harness:overview -->\n"
        "old overview generated by harness v0.1\n"
        "<!-- @hm:/harness:overview -->\n"
        "\n"
        "## My own section after the marker\n"
        "stays exactly here\n"
    )
    new = (
        "<!-- @hm:harness:overview -->\n"
        "fresh overview from v0.2\n"
        "<!-- @hm:/harness:overview -->\n"
    )
    merged, report = merge_inverted(user_owns, new)
    # Inside-marker REPLACED.
    assert "fresh overview from v0.2" in merged
    assert "old overview generated by harness v0.1" not in merged
    # Outside-marker user prose preserved byte-for-byte.
    assert "# My CLAUDE.md\n" in merged
    assert "This is my custom project description." in merged
    assert "## My own section after the marker" in merged
    assert "stays exactly here\n" in merged
    assert report.user_blocks_preserved == ["overview"]


def test_both_marker_families_coexist_orthogonally() -> None:
    """W2 — same file with both ``@hm:user:*`` AND ``@hm:harness:*``.
    Each handled per its own semantics, no cross-talk.
    """
    old = (
        "intro user prose\n"
        "<!-- @hm:harness:meta -->\n"
        "old meta\n"
        "<!-- @hm:/harness:meta -->\n"
        "<!-- @hm:user:notes -->\n"
        "user-written notes\n"
        "<!-- @hm:/user:notes -->\n"
        "trailing user prose\n"
    )
    new = (
        "<!-- @hm:harness:meta -->\n"
        "new meta\n"
        "<!-- @hm:/harness:meta -->\n"
    )
    merged, _ = merge_inverted(old, new)
    # Harness region REPLACED.
    assert "new meta" in merged
    assert "old meta" not in merged
    # User region INSIDE the file = OUTSIDE harness marker → preserved.
    assert "user-written notes" in merged
    assert "<!-- @hm:user:notes -->" in merged
    assert "<!-- @hm:/user:notes -->" in merged
    # Free user prose outside both kinds = preserved (harness inverted).
    assert "intro user prose" in merged
    assert "trailing user prose" in merged


def test_no_markers_preserves_entire_file() -> None:
    """W2 — foreign-config import path BEFORE first apply: the file has no
    harness markers yet. merge_inverted with empty NEW must preserve the
    whole OLD file byte-for-byte. The 0.11.x migration helper layered atop
    this in foreign_config.apply() is tested separately.
    """
    user_owns = "# pristine user file\n\nno markers anywhere\n"
    merged, report = merge_inverted(user_owns, "")
    assert merged == user_owns
    assert report.user_blocks_preserved == []
    assert report.user_blocks_seeded == []
    assert report.user_blocks_orphaned == []


def test_mismatched_pair_raises_marker_mismatch_error() -> None:
    """W2 — ``@hm:user:X`` opened then ``@hm:/harness:X`` closed must raise
    the typed ``MarkerMismatchError`` (subclass of ParseError) and NEVER
    silently drop the block.
    """
    text = "<!-- @hm:user:foo -->\nbody\n<!-- @hm:/harness:foo -->\n"
    with pytest.raises(MarkerMismatchError, match="Marker mismatch"):
        parse_segments(text)
    # Subclass relation: existing callers that catch ParseError still work.
    with pytest.raises(ParseError):
        parse_segments(text)


def test_nested_harness_markers_raises_typed_error() -> None:
    """Bonus W2 — nested ``@hm:harness:*`` markers forbidden, typed error."""
    text = (
        "<!-- @hm:harness:outer -->\n"
        "<!-- @hm:harness:inner -->\n"
        "x\n"
        "<!-- @hm:/harness:inner -->\n"
        "<!-- @hm:/harness:outer -->\n"
    )
    with pytest.raises(MarkerNestedError, match="Nested marker"):
        parse_segments(text)


def test_literal_hm_inside_fenced_code_block_skipped() -> None:
    """W2 — markdown file with a fenced code block containing literal
    ``@hm:harness:foo`` strings: parser must NOT treat them as markers.
    """
    text = (
        "# docs\n"
        "\n"
        "```markdown\n"
        "<!-- @hm:harness:example -->\n"
        "this is just documentation showing what a marker looks like\n"
        "<!-- @hm:/harness:example -->\n"
        "```\n"
        "\n"
        "<!-- @hm:harness:real -->\n"
        "real body\n"
        "<!-- @hm:/harness:real -->\n"
    )
    segs = parse_segments(text)
    # Only the real (outside-fence) marker is detected.
    assert len(segs) == 1
    assert segs[0].kind == BlockKind.HARNESS
    assert segs[0].id == "real"
    assert segs[0].content == "real body\n"


def test_parse_harness_blocks_filters_correctly() -> None:
    text = (
        "<!-- @hm:user:u1 -->\nU\n<!-- @hm:/user:u1 -->\n"
        "<!-- @hm:harness:h1 -->\nH\n<!-- @hm:/harness:h1 -->\n"
        "<!-- @hm:block:b1 -->\nB\n<!-- @hm:/block:b1 -->\n"
    )
    assert parse_harness_blocks(text) == {"h1": "H\n"}


def test_merge_inverted_seeds_new_harness_block_when_absent_in_old() -> None:
    """First-time apply path: OLD has no harness markers, NEW introduces one.
    merge_inverted appends the new block at end so the user can locate it.
    """
    old = "# user file\n\nno markers\n"
    new = "<!-- @hm:harness:overview -->\nfresh\n<!-- @hm:/harness:overview -->\n"
    merged, report = merge_inverted(old, new)
    assert merged.startswith("# user file\n\nno markers\n")
    assert "<!-- @hm:harness:overview -->" in merged
    assert "fresh" in merged
    assert report.user_blocks_seeded == ["overview"]


# ──────────────────────────────────────────────────────────────────────────────
# Phase 6 (auto-fix C1/C2/F2) — file-format-aware MarkerStyle dispatch
# ──────────────────────────────────────────────────────────────────────────────


def test_detect_marker_style_per_extension(tmp_path: Path) -> None:
    """File-extension dispatch: JSON → JSON_KEY, YAML → HASH_COMMENT,
    everything else → HTML_COMMENT.
    """
    assert detect_marker_style(tmp_path / "foo.json") is MarkerStyle.JSON_KEY
    assert detect_marker_style(tmp_path / "foo.yml") is MarkerStyle.HASH_COMMENT
    assert detect_marker_style(tmp_path / "foo.yaml") is MarkerStyle.HASH_COMMENT
    assert detect_marker_style(tmp_path / "foo.md") is MarkerStyle.HTML_COMMENT
    assert detect_marker_style(tmp_path / "foo.mdc") is MarkerStyle.HTML_COMMENT
    # Unknown / no extension → HTML_COMMENT (default).
    assert detect_marker_style(tmp_path / "Procfile") is MarkerStyle.HTML_COMMENT


def test_detect_marker_style_case_insensitive(tmp_path: Path) -> None:
    """Suffix matching uses lower-case so .JSON / .YML / .Md all dispatch."""
    assert detect_marker_style(tmp_path / "foo.JSON") is MarkerStyle.JSON_KEY
    assert detect_marker_style(tmp_path / "foo.YML") is MarkerStyle.HASH_COMMENT
    assert detect_marker_style(tmp_path / "foo.Md") is MarkerStyle.HTML_COMMENT


def test_yaml_hash_markers_recognized() -> None:
    """C1/C2/F2 — YAML / hash-comment marker family must parse correctly."""
    text = (
        "# preamble\n"
        "# @hm:harness:foo\n"
        "key: value\n"
        "# @hm:/harness:foo\n"
        "# tail\n"
    )
    segs = parse_segments(text, MarkerStyle.HASH_COMMENT)
    assert len(segs) == 1
    assert segs[0].kind is BlockKind.HARNESS
    assert segs[0].id == "foo"
    assert segs[0].content == "key: value\n"


def test_yaml_hash_markers_inverted_merge_replaces_inside() -> None:
    """Idempotency contract for HASH_COMMENT style: inside markers replaced,
    outside markers preserved byte-for-byte.
    """
    old = (
        "# preamble preserved\n"
        "# @hm:harness:settings\n"
        "# old: yes\n"
        "model: old-model\n"
        "# @hm:/harness:settings\n"
        "# user tail\n"
    )
    new = (
        "# @hm:harness:settings\n"
        "model: new-model\n"
        "# @hm:/harness:settings\n"
    )
    merged, report = merge_inverted(old, new, MarkerStyle.HASH_COMMENT)
    assert "model: new-model" in merged
    assert "model: old-model" not in merged
    assert "# preamble preserved" in merged
    assert "# user tail" in merged
    assert report.user_blocks_preserved == ["settings"]


def test_yaml_hash_markers_seed_appends_with_hash_syntax() -> None:
    """First-time injection in a hash-marker file: emit hash-style markers,
    not HTML.
    """
    old = "# my aider config\nmodel: gpt-4\n"
    new = "# @hm:harness:settings\nmodel: claude\n# @hm:/harness:settings\n"
    merged, report = merge_inverted(old, new, MarkerStyle.HASH_COMMENT)
    assert "# my aider config" in merged
    assert "# @hm:harness:settings" in merged
    assert "# @hm:/harness:settings" in merged
    # The HTML-comment marker must NOT appear (would confuse YAML parser).
    assert "<!--" not in merged
    assert report.user_blocks_seeded == ["settings"]


def test_yaml_hash_mismatched_pair_raises() -> None:
    """HASH_COMMENT must raise the typed MarkerMismatchError on a bad pair."""
    text = "# @hm:user:foo\nbody\n# @hm:/harness:foo\n"
    with pytest.raises(MarkerMismatchError, match="Marker mismatch"):
        parse_segments(text, MarkerStyle.HASH_COMMENT)


def test_yaml_hash_unclosed_raises() -> None:
    """HASH_COMMENT unclosed marker must raise ParseError too."""
    text = "# @hm:harness:foo\nbody\n"
    with pytest.raises(ParseError, match="Unclosed marker"):
        parse_segments(text, MarkerStyle.HASH_COMMENT)


def test_has_markers_yaml_recognizes_hash_form() -> None:
    text = "# preamble\n# @hm:harness:foo\nbody\n# @hm:/harness:foo\n"
    assert has_markers(text, MarkerStyle.HASH_COMMENT)
    # And the default HTML_COMMENT mode must NOT see it (no HTML comments).
    assert not has_markers(text, MarkerStyle.HTML_COMMENT)


def test_has_markers_json_detects_hm_harness_key() -> None:
    with_key = '{"_hm_harness": {"x": 1}, "user": 2}'
    without = '{"user": 2}'
    assert has_markers(with_key, MarkerStyle.JSON_KEY)
    assert not has_markers(without, MarkerStyle.JSON_KEY)


def test_json_key_parse_segments_when_present() -> None:
    text = '{"_hm_harness": {"managed": "yes"}, "user_key": 1}'
    segs = parse_segments(text, MarkerStyle.JSON_KEY)
    assert len(segs) == 1
    assert segs[0].kind is BlockKind.HARNESS
    assert segs[0].id == "_hm_harness"


def test_json_key_parse_segments_when_absent() -> None:
    text = '{"user_key": 1}'
    assert parse_segments(text, MarkerStyle.JSON_KEY) == []


def test_json_key_parse_segments_rejects_non_object() -> None:
    with pytest.raises(ParseError, match="top-level object"):
        parse_segments("[1, 2, 3]", MarkerStyle.JSON_KEY)


def test_json_key_parse_segments_rejects_invalid_json() -> None:
    with pytest.raises(ParseError, match="not valid JSON"):
        parse_segments("{this is not json", MarkerStyle.JSON_KEY)


def test_json_key_marker_merge() -> None:
    """C1 — old has user_key, new introduces _hm_harness; merged keeps both."""
    old = '{"user_key": 1}'
    new = '{"_hm_harness": {"managed": "yes"}}'
    merged_text, report = merge_inverted(old, new, MarkerStyle.JSON_KEY)
    merged = json.loads(merged_text)
    assert merged == {"user_key": 1, "_hm_harness": {"managed": "yes"}}
    assert report.user_blocks_seeded == ["_hm_harness"]


def test_json_key_merge_preserves_user_keys() -> None:
    """C1 — re-apply must not clobber user keys nor duplicate the harness key."""
    old = '{"user_key": 1, "_hm_harness": {"managed": "old"}}'
    new = '{"_hm_harness": {"managed": "new"}}'
    merged_text, report = merge_inverted(old, new, MarkerStyle.JSON_KEY)
    merged = json.loads(merged_text)
    assert merged == {"user_key": 1, "_hm_harness": {"managed": "new"}}
    assert report.user_blocks_preserved == ["_hm_harness"]
    assert report.user_blocks_seeded == []


def test_json_key_merge_idempotent() -> None:
    """Second apply with same NEW yields byte-identical output → caller no-op."""
    old = '{"user_key": 1, "_hm_harness": {"managed": "x"}}'
    new = '{"_hm_harness": {"managed": "x"}}'
    first, _ = merge_inverted(old, new, MarkerStyle.JSON_KEY)
    second, _ = merge_inverted(first, new, MarkerStyle.JSON_KEY)
    assert first == second


def test_json_key_merge_handles_nested_user_objects() -> None:
    """User-owned nested objects must be preserved verbatim (no merging
    inside them — only top-level keys are touched).
    """
    old = '{"models": [{"id": "user-pick"}], "_hm_harness": {"managed": "old"}}'
    new = '{"_hm_harness": {"managed": "new"}}'
    merged_text, _ = merge_inverted(old, new, MarkerStyle.JSON_KEY)
    merged = json.loads(merged_text)
    assert merged["models"] == [{"id": "user-pick"}]
    assert merged["_hm_harness"] == {"managed": "new"}


def test_json_key_merge_empty_old() -> None:
    """First-ever apply on empty file: produce the harness JSON unchanged."""
    merged_text, report = merge_inverted(
        "", '{"_hm_harness": {"managed": "x"}}', MarkerStyle.JSON_KEY
    )
    merged = json.loads(merged_text)
    assert merged == {"_hm_harness": {"managed": "x"}}
    assert report.user_blocks_seeded == ["_hm_harness"]


def test_json_key_merge_rejects_old_non_object() -> None:
    with pytest.raises(ParseError, match="top-level object"):
        merge_inverted("[1]", '{"_hm_harness": {}}', MarkerStyle.JSON_KEY)


def test_json_key_merge_rejects_new_non_object() -> None:
    with pytest.raises(ParseError, match="top-level object"):
        merge_inverted("{}", "[1]", MarkerStyle.JSON_KEY)


def test_only_user_markers_unchanged_after_style_dispatch_default() -> None:
    """ADR-009 zero-churn baseline — passing the default MarkerStyle.HTML_COMMENT
    explicitly produces the same segments as the implicit default. Confirms
    the new dispatch did not perturb the HTML happy path.
    """
    corpus = (
        "# header\n"
        "<!-- @hm:user:notes -->\n"
        "user content stays here verbatim\n"
        "<!-- @hm:/user:notes -->\n"
    )
    implicit = parse_segments(corpus)
    explicit = parse_segments(corpus, MarkerStyle.HTML_COMMENT)
    assert [(s.kind, s.id, s.content) for s in implicit] == [
        (s.kind, s.id, s.content) for s in explicit
    ]
