"""The immutable pre-change render golden for AC-003 (PLAN-plan-interview-comprehension).

Captured **before** any template edit and never regenerated by this task. Both sides of
AC-003's comparison go through :func:`_surface_baseline.render_surface`, so "pre" and
"post" are the same quantity by construction — same config source, same install-ref pin,
same frozen timestamp. A render from a synthesized default config, or without
``pinned_install_ref()``, or without ``DEFAULT_FREEZE_TIME``, differs for reasons the
whitespace contract does not address, and the executor would bisect the wrong thing.

Run standalone, once, at Phase 0::

    python -m tests.structural._comprehension_golden
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any

from harness_maker.io_utils import atomic_write

from ._surface_baseline import (
    BASE_BRANCH,
    CLAUDE_VARIANT,
    CODEX_VARIANT,
    _git,
    assert_sha_is_durable,
    render_surface,
)

_SCHEMA_VERSION = 1
_GENERATED_BY = "tests/structural/_comprehension_golden.py"

GOLDEN_PATH = Path(__file__).resolve().parent / "comprehension_zero_cost_golden.json"

#: The two commands the disclosure partial is included by, in both rendered variants.
TRACKED_COMMANDS: dict[str, tuple[str, ...]] = {
    CLAUDE_VARIANT: ("plan", "spec"),
    CODEX_VARIANT: ("hm-plan", "hm-spec"),
}


#: Provenance frontmatter that legitimately moves without the body changing. `content_hash`
#: is derived from the body, so it tracks what AC-003 actually cares about and is NOT masked.
_PROVENANCE = re.compile(r"^harness_maker_version:.*$", re.M)


def digest(text: str) -> str:
    """SHA-256 of the render with the version line masked.

    Equal character counts do not prove byte identity — two renders can differ in
    whitespace, in a swapped line, or in encoding while measuring the same length. AC-003
    says byte-identical and must be asserted that way.

    **The version line is masked, and that is the point of this docstring.** The first
    version of this golden hashed the raw render, which embeds
    `harness_maker_version:` in every command's provenance frontmatter — so the oracle broke
    on the next release bump, and broke it in the most misleading way available: `0.51.1`
    and `0.51.2` are the same LENGTH, so the render was byte-different at identical size and
    the failure read "the opt-out is not free" when nothing about the opt-out had changed.
    That is the same defect class a reviewer caught in this file's durability check — a pin
    on a quantity that moves for reasons unrelated to the claim — fixed there and left here.

    AC-003's claim is "the depth branch adds nothing at `minimal`", not "this file never
    changes". Masking the version asserts the claim; hashing it asserted the release number.
    """
    return hashlib.sha256(
        _PROVENANCE.sub("harness_maker_version: <MASKED>", text).encode()
    ).hexdigest()


def merge_base_sha() -> str:
    """The branch point, not ``HEAD``.

    ``task-land`` squash-lands ``hm/<slug>`` and deletes the branch, so a task-branch SHA
    is unreachable at base after the land and absent from a fresh clone or CI. The
    merge-base is an ancestor of the base branch by definition, so it survives.
    """
    for base in (BASE_BRANCH, f"origin/{BASE_BRANCH}"):
        if _git("rev-parse", "--verify", "--quiet", base).returncode != 0:
            continue
        proc = _git("merge-base", "HEAD", base)
        if proc.returncode == 0 and proc.stdout.strip():
            return proc.stdout.strip()
    raise RuntimeError(
        f"cannot resolve a merge-base against {BASE_BRANCH} or origin/{BASE_BRANCH}; "
        "the golden's durability cannot be established."
    )


def build_golden(depth_override: str | None = None) -> dict[str, Any]:
    surface = render_surface(depth_override=depth_override)
    missing = [
        f"{variant}/{name}"
        for variant, names in TRACKED_COMMANDS.items()
        for name in names
        if name not in surface.get(variant, {})
    ]
    if missing:
        raise RuntimeError(f"render produced no text for {missing} — refusing to freeze a hole")
    return {
        "schema_version": _SCHEMA_VERSION,
        "generated_by": _GENERATED_BY,
        "source_sha": merge_base_sha(),
        "note": (
            "AC-003 oracle. Captured before any template edit; never regenerate from this "
            "task. Compare a depth='minimal' render against these digests."
        ),
        "digests": {
            variant: {name: digest(surface[variant][name]) for name in names}
            for variant, names in TRACKED_COMMANDS.items()
        },
    }


def load_golden(path: Path | None = None) -> dict[str, Any]:
    doc: dict[str, Any] = json.loads((path or GOLDEN_PATH).read_text(encoding="utf-8"))
    return doc


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=GOLDEN_PATH)
    ap.add_argument("--print", action="store_true", dest="print_only")
    args = ap.parse_args(argv)
    doc = build_golden()
    text = json.dumps(doc, indent=2, sort_keys=True) + "\n"
    if args.print_only:
        print(text, end="")
        return 0
    assert_sha_is_durable(doc["source_sha"])
    atomic_write(args.out, text)
    print(f"wrote {args.out} at {doc['source_sha'][:12]}")
    return 0


if __name__ == "__main__":  # pragma: no cover — exercised via the CLI, not imported
    raise SystemExit(main())
