"""Phase 0 of PLAN-plan-interview-comprehension — the immutable pre-change render golden.

AC-003 asserts that ``interview.comprehension.depth: minimal`` renders byte-identically to
the pre-change output. Its oracle **must not** be ``surface_baseline.json``: that file is
this repo's render of its own ``.claude/harness.yaml``, and Phase 3b regenerates it at the
new ``standard`` default. After that regeneration the frozen ``plan``/``spec`` figures are
standard-level, so a minimal-vs-baseline comparison silently becomes minimal-vs-standard
and stops asserting anything.

This golden is therefore captured **before any template edit** and never regenerated by
this task. It records a **base-reachable** SHA (``git merge-base HEAD <base>``) rather than
the task-branch ``HEAD``: ``task-land`` squash-lands ``hm/<slug>`` and deletes the branch,
so a task-branch SHA is unreachable at base after the land and absent from a fresh clone —
the same durability defect that forces Phase 3b to exist, inverted.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from harness_maker.interview import answers_from_harness_yaml
from harness_maker.models import DEFAULT_COMPREHENSION_DEPTH

from ._comprehension_golden import (
    GOLDEN_PATH,
    TRACKED_COMMANDS,
    build_golden,
    digest,
    load_golden,
)
from ._surface_baseline import HARNESS_YAML, _git, assert_sha_is_durable, render_surface

_SHA_LEN = 64


@pytest.fixture(scope="module")
def golden() -> dict[str, object]:
    if not GOLDEN_PATH.exists():
        pytest.fail(
            f"Phase 0 golden missing at {GOLDEN_PATH}. Capture it BEFORE editing any "
            "template: python -m tests.structural._comprehension_golden"
        )
    return load_golden()


def test_the_golden_parses_and_is_not_a_stub(golden: dict[str, object]) -> None:
    """A file full of empty strings would satisfy mere existence and assert nothing."""
    raw = GOLDEN_PATH.read_text(encoding="utf-8")
    assert raw.strip(), "golden is empty — a redirection that captured a failed command"
    assert json.loads(raw) == golden
    digests = golden["digests"]
    assert isinstance(digests, dict)
    measured = {(v, c) for v, cmds in TRACKED_COMMANDS.items() for c in cmds}
    recorded = {(v, c) for v, cmds in digests.items() for c in cmds}
    assert recorded == measured, "golden's variant/command set drifted from the tracked set"
    for variant, cmds in digests.items():
        for name, value in cmds.items():
            assert isinstance(value, str), (variant, name, value)
            assert len(value) == _SHA_LEN, (variant, name, value)
            assert int(value, 16) != 0, (variant, name)


def test_the_two_commands_are_not_the_same_render(golden: dict[str, object]) -> None:
    """`plan` and `spec` digests being equal would mean the capture read one file twice."""
    digests = golden["digests"]
    assert isinstance(digests, dict)
    for variant, cmds in digests.items():
        assert len(set(cmds.values())) == len(cmds), f"{variant}: duplicate digests"


def test_the_recorded_sha_is_base_reachable(golden: dict[str, object]) -> None:
    """A task-branch SHA is deleted by `task-land` — green here, absent in CI."""
    sha = golden["source_sha"]
    assert isinstance(sha, str), f"source_sha is not a string: {sha!r}"
    assert len(sha) == 40, f"source_sha is not a full SHA: {sha!r}"
    assert_sha_is_durable(sha)


_PARTIAL_REL = "src/harness_maker/templates/agents/_partials/comprehension_block.md.j2"


def test_the_golden_is_never_regenerated_by_this_task(golden: dict[str, object]) -> None:
    """The capture must predate the template edits it is the oracle for.

    Once the partial exists, a regenerated golden would record the POST-change render and
    AC-003 would compare `minimal` against itself — the oracle would be laundered green.

    **The tamper signal is content-derived, not a SHA comparison.** An earlier version
    asserted `source_sha == merge_base_sha()`, which is green only while the work sits
    unlanded: `merge-base(HEAD, main)` is the branch point on a task branch, but once this
    squash-lands, HEAD *is* main and merge-base returns HEAD — so the frozen pre-change SHA
    would mismatch a strictly later commit and CI would go red **on the very commit that
    lands the golden**, accusing the author of regenerating it. The obvious "fix" from that
    position is to re-stamp `source_sha`, which destroys the oracle. Pinning to a moving
    quantity is what made a durability check into a scheduled false alarm.

    What does not move: at a genuine pre-change capture point the partial **did not exist**.
    A golden re-captured after the partial landed would record a commit that HAS it, and
    this fails. True forever, on any branch, before or after the land.
    """
    sha = golden["source_sha"]
    assert isinstance(sha, str)
    probe = _git("cat-file", "-e", f"{sha}:{_PARTIAL_REL}")
    assert probe.returncode != 0, (
        f"the golden's source_sha ({sha[:12]}) is a commit where {_PARTIAL_REL} already "
        "exists, so the capture post-dates the templates it is supposed to predate. The "
        "golden was re-captured after the change — AC-003 is now comparing `minimal` "
        "against itself. Restore the original capture; do NOT re-stamp the SHA."
    )


def test_the_golden_matches_a_pre_change_render_while_the_partial_is_absent() -> None:
    """While the templates are untouched, a fresh render must reproduce the golden exactly.

    This arm retires itself once Phase 2 lands: from then on the default render is
    `standard`, and AC-003's minimal comparison lives in the render gate instead.
    """
    partial = (
        Path(__file__).resolve().parents[2]
        / "src/harness_maker/templates/agents/_partials/comprehension_block.md.j2"
    )
    if partial.exists():
        pytest.skip("templates have changed — AC-003 now owns the comparison, at depth=minimal")
    fresh = build_golden()
    assert fresh["digests"] == load_golden()["digests"]


def test_digest_is_content_addressed_not_length_addressed() -> None:
    """Character count does not prove byte identity; the golden must not regress to it."""
    assert digest("ab") != digest("ba")
    assert digest("a\n") != digest("a")


def test_render_surface_supplies_both_variants_for_both_commands() -> None:
    """The tracked set must actually exist in the render, or the golden freezes nothing."""
    surface = render_surface()
    for variant, cmds in TRACKED_COMMANDS.items():
        assert variant in surface, f"variant {variant} absent from the render"
        for name in cmds:
            assert name in surface[variant], f"{variant}/{name} absent from the render"


def _configured_depth() -> str:
    """This repo's own `interview.comprehension.depth`, or the default when unset.

    Read rather than assumed, so the lever test can pick a contrast depth the config is not at.
    """
    answers = answers_from_harness_yaml(HARNESS_YAML)
    assert answers is not None, f"{HARNESS_YAML} did not parse into answers"
    comprehension = dict(answers.interview or {}).get("comprehension") or {}
    return str(comprehension.get("depth", DEFAULT_COMPREHENSION_DEPTH))


def test_the_depth_override_lever_actually_moves_the_render() -> None:
    """The golden's comparability rests entirely on this parameter working.

    The golden is captured with NO override; AC-003 compares it against
    ``render_surface(depth_override='minimal')``. If the override is a silent no-op —
    the ``model_copy`` update dropped, the key nested wrong, or ``synthesize``
    re-deriving ``interview`` from the preset and discarding it — those two calls are
    literally the same render and AC-003 goes green **by identity**, proving nothing
    about the zero-cost opt-out. That is precisely the self-comparison the SPEC's AC-003
    note forbids, arriving through a different door.

    Phase-guarded like its two siblings. The property asserted here is SPEC **S2**'s Then
    clause — a non-`minimal` depth changes the rendered text — which no Phase-1 change can
    satisfy, because until the partial exists no rendered command reads `depth` at all.
    Ungated, this would keep Phase 1's own exit criterion permanently red, and the two
    obvious ways out of that position are exactly the two things this file exists to
    forbid: editing the stage templates early, or re-capturing the golden.
    """
    partial = (
        Path(__file__).resolve().parents[2]
        / "src/harness_maker/templates/agents/_partials/comprehension_block.md.j2"
    )
    if not partial.exists():
        pytest.skip("Phase 2 has not landed — no rendered command reads depth yet")
    plain = render_surface()
    # The contrast depth is DERIVED from the repo's own configured depth, never hardcoded. An
    # earlier version pinned "deep", which held only while this repo's harness.yaml sat at
    # "standard"; the moment the config moved to "deep" the two renders became the same call and
    # this guard fired against a lever that was working perfectly. The property under test is
    # "the override moves the render", so the probe has to be a depth the config is NOT at.
    configured = _configured_depth()
    contrast = "minimal" if configured != "minimal" else "deep"
    overridden = render_surface(depth_override=contrast)
    differing = [
        (variant, name)
        for variant, names in TRACKED_COMMANDS.items()
        for name in names
        if plain[variant][name] != overridden[variant][name]
    ]
    assert differing, (
        f"render_surface(depth_override={contrast!r}) produced byte-identical output to an "
        "un-overridden render for every tracked command — the override is a no-op, so "
        "AC-003's comparison would be a render against itself."
    )


def test_minimal_reproduces_the_golden_once_the_partial_exists() -> None:
    """AC-003 proper. Inert until Phase 2, and deliberately so — before the partial, an
    un-branched template renders the same bytes at every depth, so this would pass for
    every implementation including one that ignores `depth` entirely."""
    partial = (
        Path(__file__).resolve().parents[2]
        / "src/harness_maker/templates/agents/_partials/comprehension_block.md.j2"
    )
    if not partial.exists():
        pytest.skip("Phase 2 has not landed — the depth branch does not exist yet")
    minimal = render_surface(depth_override="minimal")
    recorded = load_golden()["digests"]
    assert isinstance(recorded, dict)

    unchanged = [
        f"{variant}/{name}"
        for variant, names in TRACKED_COMMANDS.items()
        for name in names
        if digest(minimal[variant][name]) == recorded[variant][name]
    ]
    if unchanged:
        # Still the strongest available evidence for any document nothing else has edited.
        return

    # **Narrowed 2026-08-15.** Every tracked document has since been edited for reasons this
    # AC has nothing to do with, so the frozen whole-document digests no longer describe the
    # opt-out — they describe the templates' state on one past commit. Comparing against them
    # leaves exactly two moves: abandon the unrelated edit, or regenerate the oracle, which
    # `test_the_golden_is_never_regenerated_by_this_task` correctly forbids. AC-010's terminal
    # re-validation was the first stage edit to arrive after this landed and hit that wall.
    #
    # The claim itself did not need the snapshot: "the partial contributes zero bytes at
    # minimal" is checked at the partial, in `test_comprehension_render_gate`'s
    # `..._emits_the_empty_string_at_minimal`, which is a same-commit oracle and catches the
    # stray-newline hazard directly rather than as a side effect of digesting a whole file.
    #
    # The golden is NOT regenerated. Its `source_sha` provenance and its tamper check above
    # are untouched, and it stays as the historical record of the pre-change bytes.
    pytest.skip(
        "every tracked document has been edited since the capture; the zero-cost claim is "
        "asserted at the partial (test_comprehension_render_gate) rather than by a "
        "whole-document snapshot that also freezes unrelated prose"
    )
